name: Build and Deploy Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --force

    - name: Build Angular App
      run: npm run build --base-href "tour-of-heroes"

    - name: Configure Git
      run: |
        git config --global user.email "labajokerr5@gmail.com
        git config --global user.name "Kerr Labajo"

    - name: Deploy to GitHub Pages
      run: |
        npx angular-cli-ghpages --dir=dist/tour-of-heroes --no-silent

      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      